"""The deterministic triage workflow and optional model synthesis."""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Protocol

from .backend import ToolBackend, detect_test_command, issue_terms


class Synthesizer(Protocol):
    def synthesize(self, evidence: dict[str, Any]) -> str: ...


@dataclass
class TriageReport:
    issue: str
    repository_files: list[str]
    relevant_matches: list[dict[str, Any]]
    inspected_files: list[dict[str, str]]
    test_command: list[str] | None
    test_result: dict[str, Any] | None
    hypotheses: list[str]
    next_steps: list[str]
    model_summary: str | None = None
    warnings: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "issue": self.issue,
            "repository_files": self.repository_files,
            "relevant_matches": self.relevant_matches,
            "inspected_files": self.inspected_files,
            "test_command": self.test_command,
            "test_result": self.test_result,
            "hypotheses": self.hypotheses,
            "next_steps": self.next_steps,
            "model_summary": self.model_summary,
            "warnings": self.warnings,
        }

    def markdown(self) -> str:
        lines = ["# RepoPilot triage report", "", "## Issue", "", self.issue.strip(), ""]
        lines += ["## Evidence", "", f"- Repository files considered: **{len(self.repository_files)}**"]
        if self.relevant_matches:
            lines += ["- Code matches:"]
            lines += [f"  - `{item['path']}:{item['line']}` — `{item['text'].strip()}`" for item in self.relevant_matches]
        else:
            lines.append("- No literal code matches were found for the issue terms.")
        if self.inspected_files:
            lines.append("- Inspected files: " + ", ".join(f"`{item['path']}`" for item in self.inspected_files))
        lines += ["", "## Initial hypotheses", ""]
        lines += [f"{index}. {value}" for index, value in enumerate(self.hypotheses, 1)] or ["No hypothesis generated."]
        if self.test_command:
            status = "not run"
            if self.test_result is not None:
                status = "passed" if self.test_result.get("success") else "failed"
                if self.test_result.get("timed_out"):
                    status = "timed out"
            lines += ["", "## Validation", "", f"- Command: `{ ' '.join(self.test_command) }`", f"- Status: **{status}**"]
            if self.test_result and self.test_result.get("stderr"):
                lines += ["", "```text", self.test_result["stderr"].strip(), "```"]
        lines += ["", "## Suggested next steps", ""]
        lines += [f"{index}. {value}" for index, value in enumerate(self.next_steps, 1)]
        if self.model_summary:
            lines += ["", "## Model-assisted synthesis", "", self.model_summary.strip()]
        if self.warnings:
            lines += ["", "## Warnings", ""] + [f"- {warning}" for warning in self.warnings]
        lines += ["", "_Generated by RepoPilot. This report is advisory; it does not modify the repository._", ""]
        return "\n".join(lines)


class OpenAIResponsesSynthesizer:
    """Minimal dependency-free Responses API client.

    It receives evidence only; it has no tool or file-system access. This keeps
    all side effects in the deterministic, policy-controlled workflow.
    """

    def __init__(self, api_key: str, model: str = "gpt-5-mini", base_url: str = "https://api.openai.com/v1") -> None:
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")

    def synthesize(self, evidence: dict[str, Any]) -> str:
        prompt = (
            "You are a senior code triage reviewer. Based only on the JSON evidence below, "
            "write a concise diagnosis summary, explicitly separating facts from hypotheses. "
            "Do not invent files or claim that a fix was applied.\n\n"
            + json.dumps(evidence, ensure_ascii=False, indent=2)
        )
        payload = {"model": self.model, "input": prompt, "max_output_tokens": 700}
        request = urllib.request.Request(
            f"{self.base_url}/responses",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=45) as response:
                body = json.load(response)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise RuntimeError(f"model request failed: {exc}") from exc
        output_text = body.get("output_text")
        if isinstance(output_text, str) and output_text.strip():
            return output_text.strip()
        # Defensive fallback for compatible Responses implementations.
        chunks: list[str] = []
        for item in body.get("output", []):
            for content in item.get("content", []):
                if isinstance(content.get("text"), str):
                    chunks.append(content["text"])
        if not chunks:
            raise RuntimeError("model response did not contain output text")
        return "\n".join(chunks).strip()


def build_synthesizer() -> Synthesizer | None:
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key:
        return None
    return OpenAIResponsesSynthesizer(
        api_key,
        model=os.getenv("OPENAI_MODEL", "gpt-5-mini"),
        base_url=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
    )


def analyze(issue: str, backend: ToolBackend, synthesizer: Synthesizer | None = None) -> TriageReport:
    files_result = backend.list_files(".", 500)
    files = list(files_result.get("files", []))
    terms = issue_terms(issue)
    matches: list[dict[str, Any]] = []
    for term in terms[:4]:
        result = backend.search_code(term, ".", 12)
        for match in result.get("matches", []):
            if match not in matches:
                matches.append(match)
            if len(matches) >= 40:
                break
        if len(matches) >= 40:
            break

    inspected: list[dict[str, str]] = []
    for path in [match["path"] for match in matches[:5]]:
        if any(item["path"] == path for item in inspected):
            continue
        try:
            content = backend.read_file(path).get("content", "")
        except (OSError, RuntimeError, ValueError) as exc:
            continue
        inspected.append({"path": path, "excerpt": content[:2_000]})

    test_command = detect_test_command(files)
    test_result = None
    warnings: list[str] = []
    if files_result.get("truncated"):
        warnings.append("File listing reached its limit; the evidence may be incomplete.")
    if test_command:
        try:
            test_result = backend.run_test(test_command, 30_000)
        except (OSError, RuntimeError, ValueError) as exc:
            warnings.append(f"Validation command was not executed: {exc}")
    else:
        warnings.append("No supported test manifest was detected, so validation was skipped.")

    hypotheses: list[str] = []
    if matches:
        grouped = sorted({item["path"] for item in matches})
        hypotheses.append("The issue likely involves code paths in: " + ", ".join(f"`{path}`" for path in grouped[:5]) + ".")
        hypotheses.append("The matched lines are the first places to inspect; a match is evidence of relevance, not proof of root cause.")
    else:
        hypotheses.append("The issue terms did not produce literal matches; inspect naming, generated code, or external configuration next.")
    if test_result:
        hypotheses.append("The detected test command is a useful baseline, but a passing suite does not prove the reported scenario is fixed.")

    next_steps = [
        "Read the listed excerpts and reproduce the issue with the smallest failing input.",
        "Add or update a regression test before changing production code.",
        "Run the focused test first, then the full detected test command.",
    ]
    evidence = {
        "issue": issue,
        "matches": matches[:20],
        "inspected_files": inspected,
        "test_result": test_result,
    }
    model_summary = None
    if synthesizer:
        try:
            model_summary = synthesizer.synthesize(evidence)
        except RuntimeError as exc:
            warnings.append(str(exc))

    return TriageReport(
        issue=issue,
        repository_files=files,
        relevant_matches=matches,
        inspected_files=inspected,
        test_command=test_command,
        test_result=test_result,
        hypotheses=hypotheses,
        next_steps=next_steps,
        model_summary=model_summary,
        warnings=warnings,
    )
